name: hosto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  connectivity_plus: ^7.1.1
  intl: ^0.20.2
  path_provider: ^2.1.6
  flutter_slidable: ^4.0.3
  flutter_staggered_animations: ^1.1.1
  equatable: ^2.0.8
  isar_community_generator: ^3.3.2
  shared_preferences: ^2.5.5
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  mockito: ^5.6.4

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
